spawn:
  world: undefined
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0

doublejump:
  sound: BAT_TAKEOFF
  particle: ENDER_SIGNAL

join-message:
  - '&b&m-----------------------------------------------------'
  - ''
  - '&7Bienvenido a &3&lGamesHidden'
  - ''
  - '&b&m-----------------------------------------------------'